### ISSUE TITLE
I like the idea !

### ISSUE THREAD

**Issue by yezz123** [adrijano/crypto-watcher#2]
I like so much the idea about creating a GUI to show with price of crypto currency

**Comment by adrijano** [comment]
Thank you

**Comment by yezz123** [comment]
@adrijano thank you soo much for support also you can contact me on my instagram or twitter : 
IG : https://www.instagram.com/froggy__19/
Twitter : https://twitter.com/THyasser1

**Comment by adrijano** [comment]
Your respitories are good, good work bro
